import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import CardsProvider from "@/context/CardsProvider";

const roboto = Roboto({
  weight: ["100", "400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <CardsProvider>
          {children}
        </CardsProvider>
      </body>
    </html>
  );
}
