import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import CardsProvider from "@/context/CardsProvider";
import theme from "./theme";

const roboto = Roboto({
  weight: ["100", "400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ChakraProvider theme={theme}>
          <CardsProvider>
            {children}
          </CardsProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
